apiVersion: apps/v1
kind: Deployment
metadata:
  name: fydp-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fydp-app
  template:
    metadata:
      labels:
        app: fydp-app
    spec:
      containers:
      - name: fydp-app
        image: fydptestacr.azurecr.io/fydp-app:v2
        ports:
        - containerPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: fydp-app-service
spec:
  selector:
    app: fydp-app
  ports:

  - protocol: TCP
    port: 80
    targetPort: 3000

