# .github/workflows/main.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: fydptestacr  
  IMAGE_NAME: fydp-app  
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}  # Base64-encoded kubeconfig file
  KUBE_NAMESPACE: default  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}  
          password: ${{ secrets.REGISTRY_PASSWORD }}  

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.0'

      - name: Decode kubeconfig
        id: decode_kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig.yaml
        shell: bash

      - name: Configure Kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ steps.decode_kubeconfig.outputs.kubeconfig }}

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/next-app-deployment next-app=${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} -n ${{ env.KUBE_NAMESPACE }}
